apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata: 
      name: kittens-service
      labels: 
        app: nginx
        release: kittens
    spec: 
      type: ClusterIP
      ports:
        - port: 80
          name: http
          targetPort: http
      selector: 
        app: nginx
        release: kittens
  - apiVersion: v1
    kind: Service
    metadata: 
      name: dogs-service
      labels: 
        app: nginx
        release: dogs
    spec: 
      type: ClusterIP
      ports:
        - port: 80
          name: http
          targetPort: http
      selector: 
        app: nginx
        release: dogs
  - apiVersion: v1
    kind: Service
    metadata: 
      name: random-service
      labels: 
        app: nginx
    spec: 
      type: ClusterIP
      ports:
        - port: 80
          name: http
          targetPort: http
      selector: 
        app: nginx