apiVersion: v1
kind: Service
metadata: 
  name: dogs
  namespace: k8sprimitives1
  labels: 
    app: nginx
    release: dogs
spec: 
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http
  selector: 
    app: nginx
    release: dogs