apiVersion: v1
kind: Service
metadata: 
  name: kittens-nodeport
  labels: 
    app: nginx
    release: kittens
spec: 
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: http
  selector: 
    app: nginx
    release: kittens